Contributor spotlight rajiv singh
jenkins-infra/contributor-spotlight pull request #150
Opened 2024-06-28 16:01 UTC by alyssat

Create contributor spotlight story for Rajiv Singh

2024-06-28 16:10 UTC, gounthar approved these changes
Looks good to me, thanks Alyssa! 👍

2024-06-29 04:20 UTC, krisstern commented
I think Rajiv's spotlight should be turned on by updating `:page-featured: false` to `:page-featured: true`, while Harsh's spotlight should be turned off.

2024-06-29 10:33 UTC, gounthar commented
> I think Rajiv's spotlight should be turned on by updating `:page-featured: false` to `:page-featured: true`, while Harsh's spotlight should be turned off.

We should do that next week when we're ready to publish, right?

2024-06-29 10:35 UTC, lemeurherve submitted a review, later dismissed

2024-06-29 11:35 UTC, krisstern commented
> > I think Rajiv's spotlight should be turned on by updating `:page-featured: false` to `:page-featured: true`, while Harsh's spotlight should be turned off.
> 
> We should do that next week when we're ready to publish, right?

No, we don't have to wait because the changes will not be shown until the PR is merged.

2024-06-30 17:31 UTC, gounthar commented on src/pages/contributors/rajiv-singh.adoc
> +:page-featured: false
```suggestion
:page-featured: true
```

2024-07-01 19:59 UTC, alyssat commented
> I think Rajiv's spotlight should be turned on by updating `:page-featured: false` to `:page-featured: true`, while Harsh's spotlight should be turned off.

I've changed Harsh's spotlight false

2024-07-02 09:11 UTC, krisstern commented
> > I think Rajiv's spotlight should be turned on by updating `:page-featured: false` to `:page-featured: true`, while Harsh's spotlight should be turned off.
> 
> I've changed Harsh's spotlight false

Hi @alyssat Could we do that in this PR instead of a new one #152?

2024-07-02 14:59 UTC, krisstern requested changes

2024-07-02 14:59 UTC, krisstern commented on src/pages/contributors/rajiv-singh.adoc
> +:page-intro: Rajiv works as a software engineer at A.P. Moller - Maersk based in India. In 2022 he graduated from JSS Academy of Technical Education with a Bachelor in Information Science & Engineeri
```suggestion
:page-intro: Rajiv works as a software engineer at A.P. Moller - Maersk based in India. In 2022 he graduated from JSS Academy of Technical Education with a Bachelor in Information Science and Engineering. Fascinated by the extensive impact computers have on solving real world problems, he writes software for a living and has primarily worked on backend systems and infrastructure. His focus is on the fields of algorithms and distributed systems.
```

2024-07-02 16:02 UTC, krisstern approved these changes
LGTM

2024-07-02 16:03 UTC, krisstern commented
@lemeurherve Please review again and approve of the changes made

2024-07-02 19:38 UTC, lemeurherve approved these changes

2024-07-02 19:48 UTC, merged