December 27 2023 - Kris Stern contributor spotlight
jenkins-infra/contributor-spotlight pull request #44
Opened 2023-12-01 19:35 UTC by kmartens27

This pull request is to create the Contributor Spotlight page for @krisstern.

The publication date is currently set at December 27th 2023, based on the expected publication date for the next contributor spotlight.

2023-12-02 11:51 UTC, krisstern requested changes
I think we will need to set only one contributor's attribute `:page-featured:` to `true` at any one time, otherwise we will have two featured contributors like in this case.

2023-12-02 11:51 UTC, krisstern commented on src/pages/contributors/kris-stern.adoc
> +:page-image: avatar/kris-stern.jpg
```suggestion
:page-image: avatar/kris-stern.png
```

2023-12-02 11:56 UTC, krisstern requested changes

2023-12-02 11:56 UTC, krisstern commented on src/pages/contributors/kris-stern.adoc
> +:page-pronouns: They/Theirs
```suggestion
:page-pronouns: They/Them/Theirs
```

2023-12-04 22:19 UTC, kcsmalls approved these changes

2023-12-13 15:55 UTC, krisstern commented on src/pages/contributors/kris-stern.adoc
> +:page-featured: false
```suggestion
:page-featured: true
```

2023-12-17 11:48 UTC, krisstern commented
Updated the date in the latest contributor feature to January 10, 2024.

2023-12-17 11:48 UTC, krisstern approved these changes
LGTM

2023-12-18 17:32 UTC, alyssat approved these changes
LGTM. I enjoyed reading our contributor stories :)

2024-01-10 11:28 UTC, krisstern commented
@kmartens27 Checked that everything in the preview looks okay and the PR is ready to merge as scheduled today

2024-01-10 14:14 UTC, kmartens27 commented
Thanks very much @krisstern! Glad to have the final approval :)

2024-01-10 14:22 UTC, merged