December 4 2023 - creating Alex Earl spotlight
jenkins-infra/contributor-spotlight pull request #7
Opened 2023-11-20 17:59 UTC by kmartens27

This pull request is for the creation of @slide contributor spotlight page.

The date included in the title is the planned publication date of the spotlight page. This will be 2 weeks from the publication of the previous spotlight (going forward). The date of December 4 may change, depending on when the first spotlight is published. If that needs to be updated, it will be adjusted accordingly.

@slide is there another image that you would be okay with using? Currently, the profile picture on GitHub only includes your eyes/forehead area, and ideally we would have clear images to use. However, if you are not comfortable with that or have any reservations about this, we can proceed with what we have! Additionally, please provide any feedback or suggestions you might have and I'll be sure to update things as needed.

2023-11-20 18:19 UTC, slide commented
![20220802_090626](https://github.com/jenkins-infra/jenkins-contributor-spotlight/assets/55871/b62699cf-99ee-4a55-9a7e-b98017c74391)

How about this one?

2023-11-20 19:57 UTC, kmartens27 commented
That's fantastic, thanks very much @slide !

I've downloaded the image and added it accordingly

2023-11-20 20:00 UTC, lemeurherve commented
Is it normal that the image is duplicated?
Ideally, this image should be resized and optimized with compressor.io or similar.

2023-11-20 20:04 UTC, kmartens27 commented
@lemeurherve I definitely need to run it through compressor.io & resize it a bit more.

I put it in two places because there are a couple of different areas where avatars can be stored, so I was just trying to cover everything.

2023-11-20 20:17 UTC, kmartens27 commented
@lemeurherve I was able to resize and compress the image down to ~200kb

2023-11-20 21:55 UTC, MargoBGH approved these changes
LGTM!

2023-11-21 12:32 UTC, krisstern approved these changes
LGTM

2023-11-21 16:11 UTC, lemeurherve commented on src/images/avatar/alex-earl.jpg
Cf https://github.com/jenkins-infra/jenkins-contributor-spotlight/pull/9 this image can be removed.

2023-11-21 16:16 UTC, kmartens27 commented on src/images/avatar/alex-earl.jpg
Thanks @lemeurherve

2023-11-22 16:57 UTC, lemeurherve commented
Preview: https://deploy-preview-7--contributor-spotlight.netlify.app/pages/contributors/alex-earl/

2023-11-28 14:15 UTC, krisstern approved these changes

2023-11-28 15:57 UTC, lemeurherve requested changes
Requesting changes to prevent merging this PR until a week or two.

cc @kmartens27

2023-12-02 00:41 UTC, alyssat approved these changes
LGTM!

2023-12-02 11:54 UTC, krisstern requested changes

2023-12-02 11:54 UTC, krisstern commented on src/pages/contributors/alex-earl.adoc
> +:page-featured: false
```suggestion
:page-featured: true
```

2023-12-02 11:54 UTC, krisstern commented on src/pages/contributors/alex-earl.adoc
> +:page-featured: false
Then we will have to set Alex Brandes's to `:page-featured: false`

2023-12-02 11:56 UTC, krisstern commented on src/pages/contributors/alex-earl.adoc
> +:page-pronouns: He/Him/his
```suggestion
:page-pronouns: He/Him/His
```

2023-12-02 12:04 UTC, krisstern commented
Also @kmartens27 Should the publication date on which this spotlight goes out to be 2023-12-13, which is a Wednesday, or 2023-12-11, which is a Monday. I am asking because I see the others are published on a Wednesday and this one seems not to follow the prescribed pattern. Could you confirm?

2023-12-04 17:36 UTC, kmartens27 commented
@krisstern thanks for pointing that out. I had originally set it as though it would be published on a Monday. However, since we have the updated dates, I have updated this accordingly so that it matches the others.

2023-12-05 11:55 UTC, krisstern commented
@kmartens27 Is it okay for me to push a change to this PR? I see two contributors simultaneously featured but I thought we are supposed to spotlight only one at a time and would like to correct this.

2023-12-05 14:00 UTC, kmartens27 commented
@krisstern yes of course! Always feel free to make any changes you see fit. Since this has not been merged yet though, would the featured status matter? I was envisioning leaving this the way it is, and then changing the previous contributor to `false` prior to publishing this one (the next planned one). Unless there is something I'm not considering, would that be possible/appropriate?

2023-12-06 13:14 UTC, krisstern commented
> @krisstern yes of course! Always feel free to make any changes you see fit. Since this has not been merged yet though, would the featured status matter? I was envisioning leaving this the way it is, and then changing the previous contributor to `false` prior to publishing this one (the next planned one). Unless there is something I'm not considering, would that be possible/appropriate?

@kmartens27 I think it would be better to disable the spotlight for the previously featured contributor whilst we spotlight a new contributor, that way we keep it one-at-a-time. I have made the changes accordingly. Please see preview to see if this looks as expected. I will do the same for the next spotlight as well later once this one rolls out.

2023-12-06 13:15 UTC, krisstern approved these changes

2023-12-06 19:56 UTC, kmartens27 commented
Hi @krisstern that makes sense! I think we're on the same page and the change is correct. Thanks for setting that up accordingly!

2023-12-07 09:45 UTC, lemeurherve commented
@kmartens27 @krisstern should I approve this PR to unblock it or should it stay as it is until next week?

2023-12-07 11:53 UTC, lemeurherve approved these changes

2023-12-13 12:00 UTC, krisstern commented
The preview is looking great! @kmartens27 if we are publishing this today as scheduled we are all good to go!

2023-12-13 14:11 UTC, kmartens27 commented
thanks very much @krisstern, I'm merging this now so that we can get this live & send out the announcement tweet

2023-12-13 14:11 UTC, merged